python3 kin2en_ddp_trainer.py \
  -g 1 \
  --load-saved-model=false \
  --kinmt-batch-max-tokens=4096 \
  --kinmt-accumulation-steps=8 \
  --kinmt-use-bert=true \
  --kinmt-use-gpt=false \
  --use-cross-positional-attn-bias=true \
  --kinmt-use-copy-loss=false \
  --kinmt-use-names-data=true \
  --kinmt-use-foreign-terms=true \
  --kinmt-use-eval-data=false \
  --kinmt-num-train-epochs=40 \
  --kinmt-lexical-multiplier=1 \
  --kinmt-peak-lr=0.001 \
  --kinmt-warmup-steps=16000 \
  --kinmt-bert-large=true \
  --kinmt-model-name="kin2en_local_bert_base_xpos_2023-08-07"
