python3 kin2en_ddp_trainer.py \
  -g 8 \
  --load-saved-model=false \
  --kinmt-batch-max-tokens=2048 \
  --kinmt-accumulation-steps=16 \
  --kinmt-use-bert=true \
  --kinmt-use-gpt=false \
  --use-cross-positional-attn-bias=true \
  --kinmt-use-copy-loss=false \
  --kinmt-use-names-data=true \
  --kinmt-use-foreign-terms=true \
  --kinmt-use-eval-data=true \
  --kinmt-num-train-epochs=24 \
  --kinmt-peak-lr=0.0008 \
  --kinmt-model-name="kin2en_base_backtrans_bert_xpos_2023-05-02"
